package de.eightbitboy.hijacr.data.dao;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table "COMIC".
 */
public class Comic {

    private Long id;
    /** Not-null value. */
    private String key;
    /** Not-null value. */
    private String title;
    /** Not-null value. */
    private String url;
    private String randomUrl;
    /** Not-null value. */
    private String firstUrl;
    private String lastUrl;
    private String recentUrl;
    private String recentImageUrl;
    /** Not-null value. */
    private String imageQuery;
    /** Not-null value. */
    private String previousQuery;
    /** Not-null value. */
    private String nextQuery;
    private String randomQuery;
    private boolean hidden;
    private boolean favourite;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public Comic() {
    }

    public Comic(Long id) {
        this.id = id;
    }

    public Comic(Long id, String key, String title, String url, String randomUrl, String firstUrl, String lastUrl, String recentUrl, String recentImageUrl, String imageQuery, String previousQuery, String nextQuery, String randomQuery, boolean hidden, boolean favourite) {
        this.id = id;
        this.key = key;
        this.title = title;
        this.url = url;
        this.randomUrl = randomUrl;
        this.firstUrl = firstUrl;
        this.lastUrl = lastUrl;
        this.recentUrl = recentUrl;
        this.recentImageUrl = recentImageUrl;
        this.imageQuery = imageQuery;
        this.previousQuery = previousQuery;
        this.nextQuery = nextQuery;
        this.randomQuery = randomQuery;
        this.hidden = hidden;
        this.favourite = favourite;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getKey() {
        return key;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setKey(String key) {
        this.key = key;
    }

    /** Not-null value. */
    public String getTitle() {
        return title;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setTitle(String title) {
        this.title = title;
    }

    /** Not-null value. */
    public String getUrl() {
        return url;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setUrl(String url) {
        this.url = url;
    }

    public String getRandomUrl() {
        return randomUrl;
    }

    public void setRandomUrl(String randomUrl) {
        this.randomUrl = randomUrl;
    }

    /** Not-null value. */
    public String getFirstUrl() {
        return firstUrl;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setFirstUrl(String firstUrl) {
        this.firstUrl = firstUrl;
    }

    public String getLastUrl() {
        return lastUrl;
    }

    public void setLastUrl(String lastUrl) {
        this.lastUrl = lastUrl;
    }

    public String getRecentUrl() {
        return recentUrl;
    }

    public void setRecentUrl(String recentUrl) {
        this.recentUrl = recentUrl;
    }

    public String getRecentImageUrl() {
        return recentImageUrl;
    }

    public void setRecentImageUrl(String recentImageUrl) {
        this.recentImageUrl = recentImageUrl;
    }

    /** Not-null value. */
    public String getImageQuery() {
        return imageQuery;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setImageQuery(String imageQuery) {
        this.imageQuery = imageQuery;
    }

    /** Not-null value. */
    public String getPreviousQuery() {
        return previousQuery;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setPreviousQuery(String previousQuery) {
        this.previousQuery = previousQuery;
    }

    /** Not-null value. */
    public String getNextQuery() {
        return nextQuery;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setNextQuery(String nextQuery) {
        this.nextQuery = nextQuery;
    }

    public String getRandomQuery() {
        return randomQuery;
    }

    public void setRandomQuery(String randomQuery) {
        this.randomQuery = randomQuery;
    }

    public boolean getHidden() {
        return hidden;
    }

    public void setHidden(boolean hidden) {
        this.hidden = hidden;
    }

    public boolean getFavourite() {
        return favourite;
    }

    public void setFavourite(boolean favourite) {
        this.favourite = favourite;
    }

    // KEEP METHODS - put your custom methods here

	public String getSimpleUrl() {
		String simpleUrl;
		simpleUrl = url.replaceAll("/", "");
		simpleUrl = simpleUrl.replaceAll("http", "");
		simpleUrl = simpleUrl.replaceAll(":", "");
		simpleUrl = simpleUrl.replaceAll("www.", "");
		return simpleUrl;
	}
    // KEEP METHODS END

}
