package de.eightbitboy.hijacr.data.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

import de.eightbitboy.hijacr.data.dao.Comic;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "COMIC".
*/
public class ComicDao extends AbstractDao<Comic, Long> {

    public static final String TABLENAME = "COMIC";

    /**
     * Properties of entity Comic.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Key = new Property(1, String.class, "key", false, "KEY");
        public final static Property Title = new Property(2, String.class, "title", false, "TITLE");
        public final static Property Url = new Property(3, String.class, "url", false, "URL");
        public final static Property FirstUrl = new Property(4, String.class, "firstUrl", false, "FIRST_URL");
        public final static Property LastUrl = new Property(5, String.class, "lastUrl", false, "LAST_URL");
        public final static Property RecentUrl = new Property(6, String.class, "recentUrl", false, "RECENT_URL");
        public final static Property ImageQuery = new Property(7, String.class, "imageQuery", false, "IMAGE_QUERY");
        public final static Property PreviousQuery = new Property(8, String.class, "previousQuery", false, "PREVIOUS_QUERY");
        public final static Property NextQuery = new Property(9, String.class, "nextQuery", false, "NEXT_QUERY");
        public final static Property Hidden = new Property(10, boolean.class, "hidden", false, "HIDDEN");
        public final static Property Favourite = new Property(11, boolean.class, "favourite", false, "FAVOURITE");
    };


    public ComicDao(DaoConfig config) {
        super(config);
    }
    
    public ComicDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"COMIC\" (" + //
                "\"_id\" INTEGER PRIMARY KEY ," + // 0: id
                "\"KEY\" TEXT NOT NULL ," + // 1: key
                "\"TITLE\" TEXT NOT NULL ," + // 2: title
                "\"URL\" TEXT NOT NULL ," + // 3: url
                "\"FIRST_URL\" TEXT NOT NULL ," + // 4: firstUrl
                "\"LAST_URL\" TEXT," + // 5: lastUrl
                "\"RECENT_URL\" TEXT," + // 6: recentUrl
                "\"IMAGE_QUERY\" TEXT NOT NULL ," + // 7: imageQuery
                "\"PREVIOUS_QUERY\" TEXT NOT NULL ," + // 8: previousQuery
                "\"NEXT_QUERY\" TEXT NOT NULL ," + // 9: nextQuery
                "\"HIDDEN\" INTEGER NOT NULL ," + // 10: hidden
                "\"FAVOURITE\" INTEGER NOT NULL );"); // 11: favourite
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"COMIC\"";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, Comic entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindString(2, entity.getKey());
        stmt.bindString(3, entity.getTitle());
        stmt.bindString(4, entity.getUrl());
        stmt.bindString(5, entity.getFirstUrl());
 
        String lastUrl = entity.getLastUrl();
        if (lastUrl != null) {
            stmt.bindString(6, lastUrl);
        }
 
        String recentUrl = entity.getRecentUrl();
        if (recentUrl != null) {
            stmt.bindString(7, recentUrl);
        }
        stmt.bindString(8, entity.getImageQuery());
        stmt.bindString(9, entity.getPreviousQuery());
        stmt.bindString(10, entity.getNextQuery());
        stmt.bindLong(11, entity.getHidden() ? 1L: 0L);
        stmt.bindLong(12, entity.getFavourite() ? 1L: 0L);
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public Comic readEntity(Cursor cursor, int offset) {
        Comic entity = new Comic( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.getString(offset + 1), // key
            cursor.getString(offset + 2), // title
            cursor.getString(offset + 3), // url
            cursor.getString(offset + 4), // firstUrl
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5), // lastUrl
            cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6), // recentUrl
            cursor.getString(offset + 7), // imageQuery
            cursor.getString(offset + 8), // previousQuery
            cursor.getString(offset + 9), // nextQuery
            cursor.getShort(offset + 10) != 0, // hidden
            cursor.getShort(offset + 11) != 0 // favourite
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, Comic entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setKey(cursor.getString(offset + 1));
        entity.setTitle(cursor.getString(offset + 2));
        entity.setUrl(cursor.getString(offset + 3));
        entity.setFirstUrl(cursor.getString(offset + 4));
        entity.setLastUrl(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
        entity.setRecentUrl(cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6));
        entity.setImageQuery(cursor.getString(offset + 7));
        entity.setPreviousQuery(cursor.getString(offset + 8));
        entity.setNextQuery(cursor.getString(offset + 9));
        entity.setHidden(cursor.getShort(offset + 10) != 0);
        entity.setFavourite(cursor.getShort(offset + 11) != 0);
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(Comic entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(Comic entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
