package de.eightbitboy.hijacr.data.dao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import de.eightbitboy.hijacr.data.dao.Comic;

import de.eightbitboy.hijacr.data.dao.ComicDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig comicDaoConfig;

    private final ComicDao comicDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        comicDaoConfig = daoConfigMap.get(ComicDao.class).clone();
        comicDaoConfig.initIdentityScope(type);

        comicDao = new ComicDao(comicDaoConfig, this);

        registerDao(Comic.class, comicDao);
    }
    
    public void clear() {
        comicDaoConfig.getIdentityScope().clear();
    }

    public ComicDao getComicDao() {
        return comicDao;
    }

}
